import {test} from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {PGlite} from '@electric-sql/pglite';
test('Social upgrade enforces friendship, messaging, calls and Ghost privacy',async t=>{
 const db=new PGlite();
 await db.exec(`create role anon;create role authenticated;create role service_role bypassrls;
 create schema auth;create schema storage;create table auth.users(id uuid primary key);
 create function auth.uid() returns uuid language sql stable as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
 grant usage on schema auth,storage,public to anon,authenticated,service_role;
 create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
 create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text references storage.buckets,name text,unique(bucket_id,name));
 alter table storage.objects enable row level security;grant select,insert,update,delete on storage.objects to anon,authenticated;`);
 await db.exec(await readFile(new URL('../supabase/setup.sql',import.meta.url),'utf8'));
 await db.exec(await readFile(new URL('../supabase/social-upgrade.sql',import.meta.url),'utf8'));
 const A='11111111-1111-4111-8111-111111111111',B='22222222-2222-4222-8222-222222222222',C='33333333-3333-4333-8333-333333333333';
 const P='aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',M='bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb';
 const act=async id=>{await db.exec('reset role');await db.query("select set_config('request.jwt.claim.sub',$1,false)",[id??'']);await db.exec(id?'set role authenticated':'set role anon');};
 const count=async table=>Number((await db.query(`select count(*) n from ${table}`)).rows[0].n);
 const deny=sql=>assert.rejects(db.exec(sql));
 await db.exec(`insert into auth.users values('${A}'),('${B}'),('${C}')`);
 for(const [id,name] of [[A,'alice'],[B,'blake'],[C,'casey']]) {await act(id);await db.exec(`insert into profiles(id,username) values('${id}','${name}');insert into user_preferences(user_id) values('${id}')`);}
 await act(A);
 await t.test('friend request cannot start accepted',()=>deny(`insert into friendships(requester_id,addressee_id,status) values('${A}','${B}','accepted')`));
 await db.exec(`insert into friendships(requester_id,addressee_id) values('${A}','${B}')`);
 await t.test('requester cannot self-accept',async()=>assert.equal((await db.query("update friendships set status='accepted' returning id")).rows.length,0));
 await t.test('stranger cannot read pending friendship',async()=>{await act(C);assert.equal(await count('friendships'),0)});
 await t.test('nonfriend cannot create a conversation',async()=>{await act(A);await deny(`insert into conversations(member_a,member_b) values('${A}','${B}')`)});
 await t.test('recipient accepts and both become friends',async()=>{await act(B);await db.exec("update friendships set status='accepted'");assert.equal((await db.query(`select spark_private.are_friends('${A}') ok`)).rows[0].ok,true)});
 await t.test('friendship endpoints are immutable',()=>deny(`update friendships set requester_id='${C}'`));
 await t.test('reverse duplicate friendship is rejected',()=>deny(`insert into friendships(requester_id,addressee_id) values('${B}','${A}')`));
 await act(A);
 await db.exec(`insert into storage.objects(bucket_id,name) values('spark-videos','${A}/${P}.mp4');insert into posts(id,author_id,image_path,media_kind) values('${P}','${A}','${A}/${P}.mp4','video')`);
 await t.test('accepted friend can see private Reel and bytes',async()=>{await act(B);assert.equal(await count('spark_feed'),1);assert.equal(await count('storage.objects'),1)});
 await t.test('unrelated viewer cannot see private Reel',async()=>{await act(C);assert.equal(await count('spark_feed'),0);assert.equal(await count('storage.objects'),0)});
 await act(A);
 await t.test('Ghost visits are not stored even if client calls RPC',async()=>{await db.exec(`select public.spark_record_visit('${B}')`);await act(B);assert.equal(await count('profile_visits'),0)});
 await t.test('visible visit recorded only after explicit opt-in',async()=>{await act(A);await db.exec(`update user_preferences set ghost_mode=false;select public.spark_record_visit('${B}')`);await act(B);assert.equal(await count('spark_visits'),1)});
 await t.test('visitor settings are private',async()=>assert.equal(await count('user_preferences'),1));
 await t.test('visits cannot be forged by direct insert',()=>deny(`insert into profile_visits(owner_id,visitor_id) values('${B}','${C}')`));
 await t.test('disabling visit activity prevents new visits',async()=>{await db.exec('update user_preferences set visit_notifications=false');await act(C);await db.exec(`update user_preferences set ghost_mode=false;select public.spark_record_visit('${B}')`);await act(B);assert.equal(await count('profile_visits'),1)});
 await act(A);await db.exec(`insert into conversations(member_a,member_b) values('${A}','${B}')`);
 const chat=(await db.query('select id from conversations')).rows[0].id;
 await t.test('nonmember cannot see or inject messages',async()=>{await act(C);assert.equal(await count('conversations'),0);await deny(`insert into messages(conversation_id,sender_id,body) values('${chat}','${C}','intrusion')`)});
 await act(A);
 await t.test('sender cannot impersonate a friend',()=>deny(`insert into messages(conversation_id,sender_id,body) values('${chat}','${B}','spoof')`));
 await t.test('chat media requires uploaded owner object',()=>deny(`insert into messages(id,conversation_id,sender_id,media_path,media_kind) values('${M}','${chat}','${A}','${A}/${M}.mp4','video')`));
 await db.exec(`insert into storage.objects(bucket_id,name) values('spark-chat','${A}/${M}.mp4');insert into messages(id,conversation_id,sender_id,media_path,media_kind) values('${M}','${chat}','${A}','${A}/${M}.mp4','video')`);
 await t.test('recipient can read message and private attachment',async()=>{await act(B);assert.equal(await count('messages'),1);assert.equal(await count("storage.objects where bucket_id='spark-chat'"),1)});
 await t.test('recipient cannot delete senders message',async()=>assert.equal((await db.query('delete from messages returning id')).rows.length,0));
 await act(A);await db.exec(`insert into call_sessions(conversation_id,caller_id,callee_id,offer) values('${chat}','${A}','${B}','test-offer')`);
 await t.test('caller cannot fabricate recipient answer',()=>deny("update call_sessions set answer='spoof',status='accepted'"));
 await t.test('third party cannot inspect call signaling',async()=>{await act(C);assert.equal(await count('call_sessions'),0)});
 await t.test('recipient alone can answer call',async()=>{await act(B);await db.exec("update call_sessions set answer='test-answer',status='accepted'");assert.equal((await db.query('select status from call_sessions')).rows[0].status,'accepted')});
 await t.test('call participants cannot be reassigned',()=>deny(`update call_sessions set callee_id='${C}'`));
 await t.test('blocking revokes friendship, chat, call and attachment access',async()=>{await db.exec(`insert into blocks(blocker_id,blocked_id) values('${B}','${A}')`);await act(A);for(const table of ['friendships','conversations','messages','call_sessions']) assert.equal(await count(table),0);await act(B);assert.equal(await count("storage.objects where bucket_id='spark-chat'"),0);assert.equal(await count('spark_visits'),0)});
 await t.test('anonymous clients cannot call visit RPC',async()=>{await act(null);await deny(`select public.spark_record_visit('${B}')`)});
 await t.test('new tables have RLS and public functions are invoker only',async()=>{await db.exec('reset role');assert.equal(await count("pg_class c join pg_namespace n on n.oid=c.relnamespace where n.nspname='public' and c.relkind='r' and not c.relrowsecurity"),0);assert.equal(await count("pg_proc p join pg_namespace n on n.oid=p.pronamespace where n.nspname='public' and p.prosecdef"),0)});
 await db.close();
});
