begin;
create temp table spark_chat_checks(name text,passed boolean);
grant select,insert on spark_chat_checks to authenticated,service_role;
create function pg_temp.verify(ok boolean,label text) returns void language plpgsql as $$begin if ok is not true then raise exception 'FAILED: %',label;end if;insert into spark_chat_checks values(label,true);end;$$;
create function pg_temp.deny(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or check_violation then perform pg_temp.verify(true,label);return;end;raise exception 'Unexpected permission: %',label;end;$$;
select set_config('test.a',gen_random_uuid()::text,true),set_config('test.b',gen_random_uuid()::text,true),set_config('test.c',gen_random_uuid()::text,true),set_config('test.chat',gen_random_uuid()::text,true),set_config('test.post',gen_random_uuid()::text,true),set_config('test.comment',gen_random_uuid()::text,true);
insert into auth.users(id,email,raw_user_meta_data) select current_setting('test.'||who)::uuid,'spark-chat-'||current_setting('test.'||who)||'@example.invalid','{}'::jsonb from unnest(array['a','b','c'])who;
insert into public.sparknew_profiles(id,display_name) select current_setting('test.'||who)::uuid,who from unnest(array['a','b','c'])who;
insert into public.sparknew_conversations(id,user_a,user_b) values(current_setting('test.chat')::uuid,least(current_setting('test.a')::uuid,current_setting('test.b')::uuid),greatest(current_setting('test.a')::uuid,current_setting('test.b')::uuid));
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
select public.sparknew_presence_pulse();
select pg_temp.verify((select count(*)=1 from public.sparknew_presence where user_id=current_setting('test.a')::uuid),'Self presence heartbeat');
with m as(insert into public.sparknew_messages(conversation_id,sender_id,body) values(current_setting('test.chat')::uuid,current_setting('test.a')::uuid,'Receipt test') returning id) select set_config('test.message',id::text,true) from m;
select public.sparknew_mark_delivered(array[current_setting('test.message')::uuid]);
select pg_temp.verify((select delivered_at is null from public.sparknew_messages where id=current_setting('test.message')::uuid),'Sender cannot acknowledge own message');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.c'),'role','authenticated')::text,true);
select public.sparknew_mark_delivered(array[current_setting('test.message')::uuid]);
select pg_temp.verify((select count(*)=0 from public.sparknew_presence where user_id=current_setting('test.a')::uuid),'Unrelated user cannot see presence');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.b'),'role','authenticated')::text,true);
select pg_temp.verify((select delivered_at is null from public.sparknew_messages where id=current_setting('test.message')::uuid),'Nonparticipant cannot acknowledge');
select pg_temp.verify((select count(*)=1 from public.sparknew_presence where user_id=current_setting('test.a')::uuid),'Chat participant can see presence');
select public.sparknew_mark_delivered(array[current_setting('test.message')::uuid]);
select pg_temp.verify((select delivered_at is not null and seen_at is null from public.sparknew_messages where id=current_setting('test.message')::uuid),'Delivery separate from seen');
select pg_temp.deny(format('update public.sparknew_messages set delivered_at=now() where id=%L',current_setting('test.message')::uuid),'Cannot directly forge delivery timestamp');
select name,passed from spark_chat_checks;
rollback;
