begin;
create temp table spark_chat_checks(name text,passed boolean);
grant select,insert on spark_chat_checks to authenticated,service_role;
create function pg_temp.verify(ok boolean,label text) returns void language plpgsql as $$begin if ok is not true then raise exception 'FAILED: %',label;end if;insert into spark_chat_checks values(label,true);end;$$;
create function pg_temp.deny(statement text,label text) returns void language plpgsql as $$begin begin execute statement;exception when insufficient_privilege or check_violation then perform pg_temp.verify(true,label);return;end;raise exception 'Unexpected permission: %',label;end;$$;
select set_config('test.a',gen_random_uuid()::text,true),set_config('test.b',gen_random_uuid()::text,true),set_config('test.c',gen_random_uuid()::text,true),set_config('test.chat',gen_random_uuid()::text,true),set_config('test.post',gen_random_uuid()::text,true),set_config('test.comment',gen_random_uuid()::text,true);
insert into auth.users(id,email,raw_user_meta_data) select current_setting('test.'||who)::uuid,'spark-chat-'||current_setting('test.'||who)||'@example.invalid','{}'::jsonb from unnest(array['a','b','c'])who;
insert into public.sparknew_profiles(id,display_name) select current_setting('test.'||who)::uuid,who from unnest(array['a','b','c'])who;
insert into public.sparknew_conversations(id,user_a,user_b) values(current_setting('test.chat')::uuid,least(current_setting('test.a')::uuid,current_setting('test.b')::uuid),greatest(current_setting('test.a')::uuid,current_setting('test.b')::uuid));
insert into storage.objects(bucket_id,name,metadata) values('spark-media-v1',current_setting('test.a')||'/once/one.jpg','{"mimetype":"image/jpeg"}'),('spark-media-v1',current_setting('test.a')||'/once/two.jpg','{"mimetype":"image/jpeg"}');
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
insert into public.sparknew_posts(id,author_id,body) values(current_setting('test.post')::uuid,current_setting('test.a')::uuid,'Test post');
insert into public.sparknew_comments(id,post_id,author_id,body) values(current_setting('test.comment')::uuid,current_setting('test.post')::uuid,current_setting('test.a')::uuid,'Original comment');
update public.sparknew_comments set body='Edited comment' where id=current_setting('test.comment')::uuid;
select pg_temp.verify((select body='Edited comment' and edited_at is not null from public.sparknew_comments where id=current_setting('test.comment')::uuid),'Author can edit comment with server timestamp');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.b'),'role','authenticated')::text,true);
update public.sparknew_comments set body='Tampered' where id=current_setting('test.comment')::uuid;
select pg_temp.verify((select body='Edited comment' from public.sparknew_comments where id=current_setting('test.comment')::uuid),'Another user cannot edit comment');
insert into public.sparknew_comment_likes(comment_id,user_id,reaction) values(current_setting('test.comment')::uuid,current_setting('test.b')::uuid,'love');
update public.sparknew_comment_likes set reaction='haha' where comment_id=current_setting('test.comment')::uuid and user_id=current_setting('test.b')::uuid;
select pg_temp.verify((select reaction='haha' from public.sparknew_comment_likes where comment_id=current_setting('test.comment')::uuid and user_id=current_setting('test.b')::uuid),'Comment reaction can be changed without duplicates');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
update public.sparknew_comment_likes set reaction='angry' where comment_id=current_setting('test.comment')::uuid and user_id=current_setting('test.b')::uuid;
select pg_temp.verify((select reaction='haha' from public.sparknew_comment_likes where comment_id=current_setting('test.comment')::uuid and user_id=current_setting('test.b')::uuid),'Cannot change another users reaction');
with m as(insert into public.sparknew_messages(conversation_id,sender_id,body) values(current_setting('test.chat')::uuid,current_setting('test.a')::uuid,'Original message') returning id) select set_config('test.message',id::text,true) from m;
select public.sparknew_mark_seen(array[current_setting('test.message')::uuid]);
select pg_temp.verify((select seen_at is null from public.sparknew_messages where id=current_setting('test.message')::uuid),'Sender cannot mark own message seen');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.c'),'role','authenticated')::text,true);
select public.sparknew_mark_seen(array[current_setting('test.message')::uuid]);
select pg_temp.deny(format('select public.sparknew_change_message(%L,''edit'',''tampered'')',current_setting('test.message')::uuid),'Non-participant cannot edit message');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
select pg_temp.verify((select seen_at is null from public.sparknew_messages where id=current_setting('test.message')::uuid),'Third user cannot forge receipt');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.b'),'role','authenticated')::text,true);
select public.sparknew_mark_seen(array[current_setting('test.message')::uuid]);
select set_config('test.seen',(select seen_at::text from public.sparknew_messages where id=current_setting('test.message')::uuid),true);
select public.sparknew_mark_seen(array[current_setting('test.message')::uuid]);
select pg_temp.verify((select seen_at::text=current_setting('test.seen') from public.sparknew_messages where id=current_setting('test.message')::uuid),'Recipient marks seen and first seen time is retained');
select pg_temp.deny(format('select public.sparknew_change_message(%L,''unsend'','''')',current_setting('test.message')::uuid),'Recipient cannot unsend sender message');
select pg_temp.deny(format('update public.sparknew_messages set seen_at=now() where id=%L',current_setting('test.message')::uuid),'Clients cannot directly forge seen timestamps');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
select public.sparknew_change_message(current_setting('test.message')::uuid,'edit','Edited message');
select pg_temp.verify((select body='Edited message' and edited_at is not null and seen_at is not null from public.sparknew_messages where id=current_setting('test.message')::uuid),'Sender edits message and preserves receipt');
select public.sparknew_change_message(current_setting('test.message')::uuid,'unsend');
select pg_temp.verify((select body='Message unsent' and unsent_at is not null and media_path is null from public.sparknew_messages where id=current_setting('test.message')::uuid),'Unsend removes content and preserves tombstone');
select pg_temp.deny(format('select public.sparknew_change_message(%L,''edit'',''revive'')',current_setting('test.message')::uuid),'Cannot revive an unsent message');
select set_config('test.once',public.sparknew_send_once(current_setting('test.chat')::uuid,current_setting('test.a')||'/once/one.jpg','Private photo')::text,true);
select pg_temp.verify((select view_once and media_path is null from public.sparknew_messages where id=current_setting('test.once')::uuid),'View-once envelope hides storage path');
select pg_temp.verify((select count(*)=0 from storage.objects where name=current_setting('test.a')||'/once/one.jpg'),'Even uploader cannot download reserved once media through storage');
select pg_temp.deny('select * from public.sparknew_once_media','Clients cannot read one-time path vault');
select pg_temp.deny(format('select public.sparknew_claim_once(%L,%L)',current_setting('test.once')::uuid,current_setting('test.b')::uuid),'Clients cannot call privileged claim RPC');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.b'),'role','authenticated')::text,true);
select pg_temp.verify((select count(*)=0 from storage.objects where name=current_setting('test.a')||'/once/one.jpg'),'Recipient cannot bypass one-time endpoint with direct storage');
reset role;set local role service_role;
select pg_temp.verify((select public.sparknew_claim_once(current_setting('test.once')::uuid,current_setting('test.c')::uuid) is null),'Claim rejects non-participant');
select pg_temp.verify((select public.sparknew_claim_once(current_setting('test.once')::uuid,current_setting('test.a')::uuid) is null),'Sender cannot consume recipient photo');
select pg_temp.verify((select public.sparknew_claim_once(current_setting('test.once')::uuid,current_setting('test.b')::uuid)=current_setting('test.a')||'/once/one.jpg'),'Recipient first claim returns path');
select pg_temp.verify((select public.sparknew_claim_once(current_setting('test.once')::uuid,current_setting('test.b')::uuid) is null),'Second claim cannot reopen photo');
reset role;set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
select pg_temp.verify((select opened_at is not null and seen_at is not null from public.sparknew_messages where id=current_setting('test.once')::uuid),'Opened and seen timestamps reach sender');
select set_config('test.once2',public.sparknew_send_once(current_setting('test.chat')::uuid,current_setting('test.a')||'/once/two.jpg','')::text,true);
select public.sparknew_change_message(current_setting('test.once2')::uuid,'unsend');
reset role;set local role service_role;
select pg_temp.verify((select public.sparknew_claim_once(current_setting('test.once2')::uuid,current_setting('test.b')::uuid) is null),'Unsent photo cannot be claimed');
reset role;set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.b'),'role','authenticated')::text,true);
insert into public.sparknew_blocks(owner_id,target_id) values(current_setting('test.b')::uuid,current_setting('test.a')::uuid);
select pg_temp.verify((select count(*)=0 from public.sparknew_messages where conversation_id=current_setting('test.chat')::uuid),'Blocking revokes chat history access');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
select pg_temp.deny(format('select public.sparknew_change_message(%L,''edit'',''blocked'')',current_setting('test.once')::uuid),'Blocked conversation cannot edit messages');
reset role;select * from spark_chat_checks;rollback;
