begin;
create temp table checks(name text,passed boolean);grant select,insert on checks to authenticated;
create function pg_temp.verify(ok boolean,label text) returns void language plpgsql as $$begin if ok is not true then raise exception 'FAILED: %',label;end if;insert into checks values(label,true);end;$$;
create function pg_temp.deny(stmt text,label text) returns void language plpgsql as $$begin begin execute stmt;exception when insufficient_privilege then perform pg_temp.verify(true,label);return;end;raise exception 'Unexpected permission: %',label;end;$$;
select set_config('test.a',gen_random_uuid()::text,true),set_config('test.b',gen_random_uuid()::text,true),set_config('test.c',gen_random_uuid()::text,true),set_config('test.high',gen_random_uuid()::text,true),set_config('test.low',gen_random_uuid()::text,true),set_config('test.report',gen_random_uuid()::text,true);
insert into auth.users(id,email,raw_user_meta_data) select current_setting('test.'||who)::uuid,'spark-quality-'||current_setting('test.'||who)||'@example.invalid','{}'::jsonb from unnest(array['a','b','c'])who;
insert into public.sparknew_profiles(id,display_name) select current_setting('test.'||who)::uuid,who from unnest(array['a','b','c'])who;
insert into public.sparknew_badge_admins(user_id) values(current_setting('test.a')::uuid);
insert into public.sparknew_posts(id,author_id,body,kind,media_type,media_path) select current_setting('test.'||quality)::uuid,current_setting('test.b')::uuid,quality,'reel','video',current_setting('test.b')||'/'||quality||'.mp4' from unnest(array['high','low'])quality;
insert into public.sparknew_reel_playbacks(post_id,viewer_id,watched_ms,media_duration_ms) values(current_setting('test.high')::uuid,current_setting('test.c')::uuid,10000,10000),(current_setting('test.low')::uuid,current_setting('test.c')::uuid,1000,10000);
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.c'),'role','authenticated')::text,true);
select pg_temp.verify(sparknew_v1_private.reel_quality(current_setting('test.high')::uuid)>sparknew_v1_private.reel_quality(current_setting('test.low')::uuid),'Watch completion improves ranking');
select pg_temp.verify((select h.ordinality<l.ordinality from public.sparknew_ranked_reels(0,40) with ordinality h cross join public.sparknew_ranked_reels(0,40) with ordinality l where h.id=current_setting('test.high')::uuid and l.id=current_setting('test.low')::uuid),'Ranked feed places high retention reel first');
select set_config('test.score',sparknew_v1_private.reel_quality(current_setting('test.high')::uuid)::text,true);
select public.sparknew_record_reel_playback(current_setting('test.high')::uuid,10000,10000);
select pg_temp.verify(sparknew_v1_private.reel_quality(current_setting('test.high')::uuid)=current_setting('test.score')::numeric,'Repeated identical plays do not inflate quality');
select pg_temp.verify((select count(*)=0 from public.sparknew_reel_playbacks where post_id=current_setting('test.high')::uuid),'Ranking does not expose raw viewers');
with r as(insert into public.sparknew_reports(reporter_id,target_type,target_id,reason) values(auth.uid(),'post',current_setting('test.high')::uuid,'Test review') returning id)select set_config('test.report',id::text,true) from r;
select pg_temp.deny(format('select public.sparknew_review_report(%L,''hide'')',current_setting('test.report')),'Nonadmin cannot moderate');
select pg_temp.deny(format('update public.sparknew_posts set moderation_hidden=false where id=%L',current_setting('test.high')),'Client cannot change hidden flag');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
select pg_temp.verify((select count(*)=1 from public.sparknew_reports where id=current_setting('test.report')::uuid),'Admin can review reports');
select public.sparknew_review_report(current_setting('test.report')::uuid,'hide');
select pg_temp.verify((select count(*)=0 from public.sparknew_posts where id=current_setting('test.high')::uuid),'Hidden content disappears through RLS');
select pg_temp.verify(sparknew_v1_private.reel_quality(current_setting('test.high')::uuid)=0,'Hidden content quality is not exposed');
select public.sparknew_review_report(current_setting('test.report')::uuid,'restore');
select pg_temp.verify((select count(*)=1 from public.sparknew_posts where id=current_setting('test.high')::uuid),'Admin can restore content');
select pg_temp.verify((select status='restored' and resolved_by=auth.uid() from public.sparknew_reports where id=current_setting('test.report')::uuid),'Moderator action recorded');
select name,passed from checks;
rollback;
