-- Non-destructive: all synthetic users, rows and helper functions roll back.
begin;
create temp table spark_test_results(name text,passed boolean);
grant select,insert on spark_test_results to authenticated;
create function pg_temp.check_true(value boolean,label text) returns void language plpgsql as $$ begin
 if value is not true then raise exception 'FAILED: %',label;end if;
 insert into spark_test_results values(label,true);
end; $$;
create function pg_temp.must_deny(statement text,label text) returns void language plpgsql as $$
declare denied boolean=false;
begin
 begin execute statement; exception when insufficient_privilege then denied=true;end;
 perform pg_temp.check_true(denied,label);
end; $$;
select set_config('spark.test.alice',gen_random_uuid()::text,true),set_config('spark.test.bob',gen_random_uuid()::text,true),set_config('spark.test.carol',gen_random_uuid()::text,true);
insert into auth.users(id,email,raw_user_meta_data) select current_setting('spark.test.'||who)::uuid,'spark-test-'||current_setting('spark.test.'||who)||'@example.invalid','{}'::jsonb from unnest(array['alice','bob','carol']) who;
insert into public.sparknew_profiles(id,display_name) select current_setting('spark.test.'||who)::uuid,who from unnest(array['alice','bob','carol']) who;
select pg_temp.check_true((select count(*)=17 and bool_and(relrowsecurity) from pg_class where relnamespace='public'::regnamespace and relname like 'sparknew_%' and relkind='r'),'RLS enabled on all 17 new tables');
select pg_temp.check_true((select not public from storage.buckets where id='spark-media-v1'),'Media bucket is private');
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('spark.test.alice'),'role','authenticated')::text,true);
insert into public.sparknew_posts(author_id,body,visibility,media_path,media_type) values(current_setting('spark.test.alice')::uuid,'private test','private',current_setting('spark.test.alice')||'/private.jpg','image');
insert into public.sparknew_posts(author_id,body,visibility) values(current_setting('spark.test.alice')::uuid,'friends test','friends'),(current_setting('spark.test.alice')::uuid,'public test','public');
insert into public.sparknew_posts(author_id,body,kind) values(current_setting('spark.test.alice')::uuid,'story test','story');
select pg_temp.check_true((select count(*)=4 from public.sparknew_posts where author_id=current_setting('spark.test.alice')::uuid),'Owner sees all own posts');
select pg_temp.check_true((select expires_at between now()+interval '23 hours' and now()+interval '25 hours' from public.sparknew_posts where body='story test'),'Story expiry is assigned by the database');
select pg_temp.must_deny(format('insert into public.sparknew_posts(author_id,body) values(%L,''spoofed'')',current_setting('spark.test.bob')),'Cannot impersonate another post author');
select pg_temp.must_deny(format('insert into public.sparknew_posts(author_id,body,media_path,media_type) values(%L,''stolen'',%L,''image'')',current_setting('spark.test.alice'),current_setting('spark.test.bob')||'/stolen.jpg'),'Cannot attach another users media');
insert into public.sparknew_friendships(sender_id,receiver_id) values(current_setting('spark.test.alice')::uuid,current_setting('spark.test.bob')::uuid);
update public.sparknew_friendships set status='accepted' where sender_id=current_setting('spark.test.alice')::uuid;
select pg_temp.check_true((select status='pending' from public.sparknew_friendships where sender_id=current_setting('spark.test.alice')::uuid),'Sender cannot accept own friend request');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('spark.test.bob'),'role','authenticated')::text,true);
select pg_temp.check_true((select count(*)=2 from public.sparknew_posts where author_id=current_setting('spark.test.alice')::uuid),'Stranger sees public post and public story only');
select pg_temp.check_true(not sparknew_v1_private.media_visible(current_setting('spark.test.alice')||'/private.jpg'),'Private post media hidden from strangers');
update public.sparknew_friendships set status='accepted' where receiver_id=current_setting('spark.test.bob')::uuid;
select pg_temp.check_true((select status='accepted' from public.sparknew_friendships where receiver_id=current_setting('spark.test.bob')::uuid),'Recipient can accept request');
select pg_temp.check_true((select count(*)=3 from public.sparknew_posts where author_id=current_setting('spark.test.alice')::uuid),'Accepted friend sees friends-only post');
select pg_temp.must_deny(format('update public.sparknew_posts set author_id=%L where body=''public test''',current_setting('spark.test.bob')),'Post ownership cannot be reassigned');
insert into public.sparknew_comments(post_id,author_id,body) select id,current_setting('spark.test.bob')::uuid,'test comment' from public.sparknew_posts where body='friends test';
select pg_temp.check_true((select count(*)=1 from public.sparknew_comments where body='test comment'),'Friend can comment on visible post');
insert into public.sparknew_conversations(user_a,user_b) values(least(current_setting('spark.test.alice')::uuid,current_setting('spark.test.bob')::uuid),greatest(current_setting('spark.test.alice')::uuid,current_setting('spark.test.bob')::uuid));
select set_config('spark.test.chat',(select id::text from public.sparknew_conversations where user_a=least(current_setting('spark.test.alice')::uuid,current_setting('spark.test.bob')::uuid)),true);
insert into public.sparknew_messages(conversation_id,sender_id,body,media_path,media_type) values(current_setting('spark.test.chat')::uuid,current_setting('spark.test.bob')::uuid,'private chat',current_setting('spark.test.bob')||'/chat.jpg','image');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('spark.test.alice'),'role','authenticated')::text,true);
select pg_temp.check_true((select count(*)=1 from public.sparknew_messages where conversation_id=current_setting('spark.test.chat')::uuid),'Conversation recipient reads message');
select pg_temp.check_true(sparknew_v1_private.media_visible(current_setting('spark.test.bob')||'/chat.jpg'),'Conversation recipient reads chat media');
select pg_temp.check_true((select count(*)>=3 from public.sparknew_notifications where recipient_id=current_setting('spark.test.alice')::uuid),'Server creates recipient notifications');
select pg_temp.must_deny(format('insert into public.sparknew_notifications(recipient_id,actor_id,kind) values(%L,%L,''forged'')',current_setting('spark.test.alice'),current_setting('spark.test.bob')),'Clients cannot forge notifications');
insert into public.sparknew_calls(conversation_id,caller_id,callee_id) values(current_setting('spark.test.chat')::uuid,current_setting('spark.test.alice')::uuid,current_setting('spark.test.bob')::uuid);
select set_config('spark.test.call',(select id::text from public.sparknew_calls where conversation_id=current_setting('spark.test.chat')::uuid),true);
select set_config('request.jwt.claims',json_build_object('sub',current_setting('spark.test.carol'),'role','authenticated')::text,true);
select pg_temp.check_true((select count(*)=0 from public.sparknew_messages where conversation_id=current_setting('spark.test.chat')::uuid),'Third user cannot read conversation messages');
select pg_temp.check_true((select count(*)=0 from public.sparknew_calls where id=current_setting('spark.test.call')::uuid),'Third user cannot read call signaling');
select pg_temp.check_true(not sparknew_v1_private.media_visible(current_setting('spark.test.bob')||'/chat.jpg'),'Third user cannot read chat media');
select pg_temp.must_deny(format('insert into public.sparknew_messages(conversation_id,sender_id,body) values(%L,%L,''intrusion'')',current_setting('spark.test.chat'),current_setting('spark.test.carol')),'Third user cannot send into conversation');
select pg_temp.must_deny(format('insert into public.sparknew_ice(call_id,user_id,candidate) values(%L,%L,''{}'')',current_setting('spark.test.call'),current_setting('spark.test.carol')),'Third user cannot inject call candidates');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('spark.test.bob'),'role','authenticated')::text,true);
update public.sparknew_calls set answer='{"type":"answer","sdp":"test"}',status='accepted' where id=current_setting('spark.test.call')::uuid;
select pg_temp.check_true((select status='accepted' from public.sparknew_calls where id=current_setting('spark.test.call')::uuid),'Call recipient can answer');
insert into public.sparknew_blocks(owner_id,target_id) values(current_setting('spark.test.bob')::uuid,current_setting('spark.test.alice')::uuid);
select pg_temp.check_true((select count(*)=0 from public.sparknew_posts where author_id=current_setting('spark.test.alice')::uuid),'Blocking hides blocked authors posts');
select pg_temp.check_true((select count(*)=0 from public.sparknew_messages where conversation_id=current_setting('spark.test.chat')::uuid),'Blocking revokes conversation access');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('spark.test.alice'),'role','authenticated')::text,true);
select pg_temp.check_true((select count(*)=0 from public.sparknew_profiles where id=current_setting('spark.test.bob')::uuid),'Block is enforced in both directions');
select pg_temp.check_true(not sparknew_v1_private.media_visible(current_setting('spark.test.bob')||'/chat.jpg'),'Block revokes chat media access');
reset role;
select json_build_object('passed',count(*),'checks',json_agg(name)) as verification from spark_test_results;
rollback;
