begin;
create temp table spark_connection_checks(name text,passed boolean);
grant select,insert on spark_connection_checks to authenticated;
create function pg_temp.verify(ok boolean,label text) returns void language plpgsql as $$begin
 if ok is not true then raise exception 'FAILED: %',label;end if;
 insert into spark_connection_checks values(label,true);
end;$$;
select set_config('test.a',gen_random_uuid()::text,true),set_config('test.b',gen_random_uuid()::text,true),set_config('test.c',gen_random_uuid()::text,true);
insert into auth.users(id,email,raw_user_meta_data) select current_setting('test.'||who)::uuid,'spark-connections-'||current_setting('test.'||who)||'@example.invalid','{}'::jsonb from unnest(array['a','b','c'])who;
insert into public.sparknew_profiles(id,display_name) select current_setting('test.'||who)::uuid,who from unnest(array['a','b','c'])who;
set local role authenticated;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
select pg_temp.verify((select followers=0 and following=0 and friends=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'New profile starts with zero connections');
insert into public.sparknew_friendships(sender_id,receiver_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid);
select pg_temp.verify((select following=1 and followers=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Request sender follows recipient');
select pg_temp.verify((select followers=1 and following=0 from public.sparknew_profile_counts(current_setting('test.b')::uuid)),'Recipient gains follower before acceptance');
select pg_temp.verify((select id=current_setting('test.b')::uuid from public.sparknew_profile_people(current_setting('test.a')::uuid,'following')),'Following list contains recipient');
insert into public.sparknew_follows(follower_id,following_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid);
select pg_temp.verify((select followers=1 from public.sparknew_profile_counts(current_setting('test.b')::uuid)),'Manual follow and pending request deduplicate');
update public.sparknew_friendships set status='accepted' where sender_id=current_setting('test.a')::uuid and receiver_id=current_setting('test.b')::uuid;
select pg_temp.verify((select friends=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Sender cannot accept own request');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.b'),'role','authenticated')::text,true);
update public.sparknew_friendships set status='accepted' where sender_id=current_setting('test.a')::uuid and receiver_id=current_setting('test.b')::uuid;
select pg_temp.verify((select followers=1 and following=0 and friends=1 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Accepted sender gets follower and no following');
select pg_temp.verify((select followers=1 and following=0 and friends=1 from public.sparknew_profile_counts(current_setting('test.b')::uuid)),'Accepted recipient gets follower and no following');
select pg_temp.verify((select id=current_setting('test.a')::uuid from public.sparknew_profile_people(current_setting('test.b')::uuid,'friends')),'Friends list shows accepted connection');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.c'),'role','authenticated')::text,true);
select pg_temp.verify((select count(*)=0 from public.sparknew_friendships where sender_id=current_setting('test.a')::uuid),'Raw relationship rows stay private');
select pg_temp.verify((select id=current_setting('test.b')::uuid from public.sparknew_profile_people(current_setting('test.a')::uuid,'friends')),'Profile exposes sanitized public friends');
insert into public.sparknew_blocks(owner_id,target_id) values(current_setting('test.c')::uuid,current_setting('test.b')::uuid);
select pg_temp.verify((select followers=0 and friends=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Viewer block hides connection in lists and counts');
select pg_temp.verify((select followers=0 and friends=0 and posts=0 from public.sparknew_profile_counts(current_setting('test.b')::uuid)),'Blocked target exposes no counts');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
delete from public.sparknew_friendships where sender_id=current_setting('test.a')::uuid and receiver_id=current_setting('test.b')::uuid;
select pg_temp.verify((select followers=0 and following=1 and friends=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Unfriend removes automatic follow but preserves explicit follow');
select pg_temp.verify((select followers=1 and following=0 and friends=0 from public.sparknew_profile_counts(current_setting('test.b')::uuid)),'Independent manual follower remains');
delete from public.sparknew_follows where follower_id=current_setting('test.a')::uuid and following_id=current_setting('test.b')::uuid;
insert into public.sparknew_friendships(sender_id,receiver_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid);
delete from public.sparknew_friendships where sender_id=current_setting('test.a')::uuid and receiver_id=current_setting('test.b')::uuid;
select pg_temp.verify((select following=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Cancel request removes automatic following');
select pg_temp.verify((select followers=0 from public.sparknew_profile_counts(current_setting('test.b')::uuid)),'Cancel request removes automatic follower');
insert into public.sparknew_friendships(sender_id,receiver_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid);
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.b'),'role','authenticated')::text,true);
delete from public.sparknew_friendships where sender_id=current_setting('test.a')::uuid and receiver_id=current_setting('test.b')::uuid;
select pg_temp.verify((select following=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Decline removes automatic following');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.a'),'role','authenticated')::text,true);
insert into public.sparknew_friendships(sender_id,receiver_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid);
insert into public.sparknew_blocks(owner_id,target_id) values(current_setting('test.a')::uuid,current_setting('test.b')::uuid);
select pg_temp.verify((select following=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Block suppresses pending follow');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.b'),'role','authenticated')::text,true);
select pg_temp.verify((select followers=0 from public.sparknew_profile_counts(current_setting('test.b')::uuid)),'Reverse block suppresses follower');
select set_config('request.jwt.claims','{}',true);
select pg_temp.verify((select followers=0 and following=0 and friends=0 and posts=0 from public.sparknew_profile_counts(current_setting('test.a')::uuid)),'Missing identity reveals nothing');
reset role;
select pg_temp.verify((select not has_function_privilege('anon','public.sparknew_profile_counts(uuid)','EXECUTE')),'Anonymous RPC execution denied');
select * from spark_connection_checks;
rollback;
